import { red, orange, blue, pink, grey, green } from "@material-ui/core/colors";
import colors from "Themes/ThemeColors";
const menuLists = {
  HOME: {
    title: "Home",
    code: "home",
    icon: "fas fa-home",
    iconSize: "24px",
    iconColor: colors.blue,
    iconBgColor: blue[100],
    redirect: "/",
    show: true,
  },
  PROFILE: {
    title: "Profile",
    code: "profile",
    icon: "far fa-user-circle",
    iconSize: "24px",
    iconColor: colors.blue,
    iconBgColor: blue[100],
    redirect: "/profile",
    show: true,
  },
  QUESTIONS: {
    title: "Feed",
    code: "questions",
    icon: "fas fa-rss",
    iconSize: "22px",
    iconColor: orange[500],
    iconBgColor: orange[100],
    redirect: "/questions",
    show: true,
  },
  BLOODBANK: {
    title: "Blood Bank",
    code: "bloodbank",
    icon: "fas fa-tint",
    iconSize: "24px",
    iconColor: red[500],
    iconBgColor: red[100],
    redirect: "/bloodbank",
    show: true,
  },
  ABOUT: {
    title: "About",
    code: "about",
    icon: "fas fa-info",
    iconSize: "24px",
    iconColor: colors.blue,
    iconBgColor: blue[100],
    redirect: "/about",
    show: true,
  },
  SETTINGS: {
    title: "Settings",
    code: "settings",
    icon: "fas fa-cog",
    iconSize: "24px",
    iconColor: grey[700],
    redirect: "/settings",
    show: true,
  },
  JOBS: {
    title: "Jobs",
    code: "jobs",
    icon: "fas fa-briefcase",
    iconSize: "24px",
    iconColor: pink[500],
    iconBgColor: pink[100],
    redirect: "/settings",
    show: true,
  },
  ONLINESHOP: {
    title: "Online Shop",
    code: "onlineShop",
    icon: "fas fa-shopping-cart",
    iconSize: "20px",
    iconColor: green[500],
    iconBgColor: green[100],
    redirect: "/onlineShop",
    show: true,
  },
  BLOG: {
    title: "Blog",
    code: "blog",
    icon: "fab fa-blogger",
    iconSize: "24px",
    iconColor: red[500],
    iconBgColor: red[100],
    redirect: "/settings",
    show: true,
  },
  RECIPES: {
    title: "Recipes",
    code: "recipes",
    icon: "fas fa-utensils",
    iconSize: "24px",
    iconColor: orange[500],
    iconBgColor: orange[100],
    redirect: "/settings",
    show: true,
  },
};
export default menuLists;
